{
 "title": "Live MQTT Data from Sensors",
 "time": { "from": "now/d", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Temperature",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "alias": "Temperature",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "MQTT_Temperature",
     "select": [
      [
       { "params": [ "Temperature" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "MQTT_Humidity",
     "select": [
      [
       { "params": [ "Humidity" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Temperature and Humidity Past hour",
   "type": "graph",
   "gridPos": { "h": 5, "w": 18, "x": 6, "y": 0 },
   "yaxes": [
    { "format": "degree", "label": "Temperature" }
   ],
   "targets": [
    {
     "alias": "Humidity",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "MQTT_Humidity",
     "select": [
      [
       { "params": [ "Humidity" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Temperature",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "MQTT_Temperature",
     "select": [
      [
       { "params": [ "Temperature" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": " Temperature and Humidity Past 24 hours",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "humidity", "label": "Humidity" }
   ],
   "targets": [
    {
     "alias": "Humidity",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "MQTT_Humidity",
     "select": [
      [
       { "params": [ "Humidity" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Temperature",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "MQTT_Temperature",
     "select": [
      [
       { "params": [ "Temperature" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Humidity past 7 days",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "humidity", "label": "Humidity" }
   ],
   "targets": [
    {
     "alias": "Humidity",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "MQTT_Humidity",
     "select": [
      [
       { "params": [ "Humidity" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Temperature past 7 days",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "degree", "label": "Temperature" }
   ],
   "targets": [
    {
     "alias": "Temperature",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "MQTT_Temperature",
     "query": "SELECT last(\"value\") - first(\"value\") FROM \"m3\" WHERE (\"entity_id\" = 'gas_consumption') AND $timeFilter GROUP BY time(1d)\n",
     "select": [
      [
       { "params": [ "Temperature" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}