{
 "title": "OPCUA Readings Analysis",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "OMRONCP2E (PLC 1)",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 0 },
   "format": "s",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"TotalTime\") FROM \"OMRONCP2E_Timer\"  WHERE $timeFilter GROUP BY time(60m), \"Type\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "PLC 1 Status Run",
   "type": "natel-discrete-panel",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "alias": "Status Run",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "OMRONCP2E",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "switch", "operator": "=", "value": "Status_Run" }
     ]
    }
   ]
  },
  {
   "title": "PLC 1 Status Stop",
   "type": "natel-discrete-panel",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 4 },
   "targets": [
    {
     "alias": "Status Stop",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "OMRONCP2E",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "switch", "operator": "=", "value": "Status_Stop" }
     ]
    }
   ]
  },
  {
   "title": "PLC 1 Status Ready",
   "type": "natel-discrete-panel",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "alias": "Status Ready",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "OMRONCP2E",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "switch", "operator": "=", "value": "Step_Ready" }
     ]
    }
   ]
  },
  {
   "title": "OMRONCP1L (PLC 2)",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 12 },
   "format": "s",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"TotalTime\") FROM \"OMRONCP1L_Timer\"  WHERE $timeFilter GROUP BY time(60m), \"Type\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "PLC 2 Status Run",
   "type": "natel-discrete-panel",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 12 },
   "targets": [
    {
     "alias": "Status Run",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "OMRONCP1L",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "switch", "operator": "=", "value": "Status_Run" }
     ]
    }
   ]
  },
  {
   "title": "PLC 2 Status Stop",
   "type": "natel-discrete-panel",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "alias": "Status Stop",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "OMRONCP1L",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "switch", "operator": "=", "value": "Status_Stop" }
     ]
    }
   ]
  },
  {
   "title": "PLC 2 Status Ready",
   "type": "natel-discrete-panel",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 20 },
   "targets": [
    {
     "alias": "Status Ready",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "OMRONCP1L",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "switch", "operator": "=", "value": "Step_Ready" }
     ]
    }
   ]
  },
  {
   "title": "OMRONCP1L-M (PLC 3)",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 24 },
   "format": "s",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"TotalTime\") FROM \"OMRONCP1LM_Timer\"  WHERE $timeFilter GROUP BY time(60m), \"Type\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "PLC 3 Status Run",
   "type": "natel-discrete-panel",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "alias": "Status Run",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "OMRONCP1LM",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "switch", "operator": "=", "value": "Status_Run" }
     ]
    }
   ]
  },
  {
   "title": "PLC 3 Status Stop",
   "type": "natel-discrete-panel",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 28 },
   "targets": [
    {
     "alias": "Status Stop",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "OMRONCP1LM",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "switch", "operator": "=", "value": "Status_Stop" }
     ]
    }
   ]
  },
  {
   "title": "PLC 3 Status Ready",
   "type": "natel-discrete-panel",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 32 },
   "targets": [
    {
     "alias": "Status Ready",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "OMRONCP1LM",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "switch", "operator": "=", "value": "Step_Ready" }
     ]
    }
   ]
  }
 ]
}